on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: SSH to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 13.127.248.85
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            set -e

            sudo apt update

            # Clone or pull BiteHaven
            if [ -d "BiteHaven/.git" ]; then
              echo "Updating BiteHaven repo..."
              cd BiteHaven
              git pull origin main
            else
              echo "Cloning BiteHaven repo..."
              git clone https://github.com/005abhi/BiteHaven
              cd BiteHaven

            fi

            pkill -9 node || true


            cd frontend
            npm cache clean --force
            npm install
            nohup npm run dev > frontend.log 2>&1 &

            cd ../backend
            npm cache clean --force
            npm install
            nohup npm run dev > backend.log 2>&1 &
